## Welcome To Coding Exercise 5

**You only need to answer 2 question**

Hari ini, kita sedang membahas library yang sangat penting dalam Python yang disebut `numpy`. Minggu depan, kita akan membahas library lain yang sangat penting di Python bernama `pandas`. Untuk Latihan 9 dan 10, tidak akan ada pengkodean `R`.

Kita akan kembali ke `R` di Day 11.

Sebagai referensi, kedua library ini menjadi syarat utama Data Scientist di perusahaan teknologi papan atas Indonesia - sedangkan R tidak tercantum dalam persyaratan.

Jadi, sangat penting untuk menguasai kedua library ini.

In [ ]:
# !pip install -U IPython

In [ ]:
# from IPython.display import Image
# Image(url= "img/image1.jpg", width=400, height=400)

In [ ]:
# from IPython.display import Image
# Image(url= "img/image2.jpg", width=400, height=400)

![image1.jpg](https://drive.google.com/uc?id=1_T8LPxMaYq06uW9JNqOy6Y0yIu_p9EZU)

![image2.jpg](https://drive.google.com/uc?id=15E-Od0G_2eqvCnR9t8Div5V4adnGbswA)

### Numpy Question 1

In [ ]:
import numpy as np

Fungsi Anda akan disebut `display_max`. Input Anda akan berupa `numpy array`. Output Anda akan memberi tahu di mana indeks adalah nilai maksimum dari setiap baris. Pisahkan output untuk setiap baris dengan koma.

Jika ada lebih dari satu nilai maksimum, beri tahu posisi kejadian PERTAMA saja.

#### Example 1

Input array: `[[1,2,3,4,3], [5,10,8,3,2], [-5,7,8.4,1,0]]`

Output: 3, 1, 2

Penjelasan:

- Baris pertama, `[1,2,3,4,3]`, memiliki nilai maksimum `4` pada indeks = 3 (Ingat! Ini Python. Indeks dimulai dari 0)

- Baris kedua, `[5,10,8,3,2]`, memiliki nilai maksimum `10` pada indeks = 1

- Baris ketiga, `[-5,7,8.4,1,0]`, memiliki nilai maksimum `8,4` pada indeks = 2

Jadi, output Anda akan '3,1,2'

#### Example 2

Input array = `[[5,10,1,3], [1,5,1,5], [0,3,1,8]]`

Output: 1,1,3

Penjelasan:

- Baris pertama, `[5,10,1,3]` memiliki nilai maksimum `10` pada indeks = 1
- Baris kedua, `[1,5,1,5]` memiliki nilai maksimum `5` pada indeks = 1, 3. Tetapi kita hanya perlu mencetak kemunculan pertama, jadi kita hanya mencetak indeks = 1.
- Baris ketiga, `[0,3,1,8]` memiliki nilai maksimum `8` pada indeks = 3.

Jadi, output Anda akan '1,1,3'

#### Constrains:
- Jumlah baris bisa bilangan bulat berapa saja. Kita dapat memiliki input array dalam berbagai bentuk dan ukuran.

In [ ]:
def display_max(input_array):
    ### Write your solution here ###
    output = []
    for row in input_array:
        max_val = np.max(row)
        max_idx = np.where(row == max_val)[0][0]
        output.append(str(max_idx))
    return ', '.join(output)

In [ ]:
# Example 1
input_array1 = np.array([[1, 2, 3, 4, 3], [5, 10, 8, 3, 2], [-5, 7, 8.4, 1, 0]])
output1 = display_max(input_array1)
print(output1)

3, 1, 2


In [ ]:
# Example 2
input_array2 = np.array([[5, 10, 1, 3], [1, 5, 1, 5], [0, 3, 1, 8]])
output2 = display_max(input_array2)
print(output2)

1, 1, 3


### Numpy Question 2


##### Reminder untuk Class Managers and Students. ####

Jika solusi memiliki perulangan `for`,`while`, Anda tidak mendapatkan poin penuh. Tujuan dari latihan ini adalah untuk menghindari perulangan saat melakukan hal-hal yang membutuhkan kondisi tertentu.

#### Instructions: ####

Fungsi Anda akan bernama `grade`. Input Anda akan berupa array di mana setiap baris menunjukkan skor siswa. Output Anda akan berupa array DENGAN UKURAN YANG SAMA PERSIS dengan array input, tetapi hanya diisi dengan 'P' dan 'F'.

- Jika nilai >= 70, maka untuk tes tersebut siswa dinyatakan lulus. Kita beri simbol 'P' untuk menandakan bahwa siswa tersebut lulus.
- Jika skornya < 70, maka untuk tes tersebut, siswa tersebut gagal. Kita beri simbol 'F', untuk menandakan bahwa siswa tersebut gagal.

#### Example 1:

In [ ]:
input_array = np.array([[80,50,80,60,70],
                       [100,90,80,70,50],
                       [70,70,60,50,85]])
input_array

array([[ 80,  50,  80,  60,  70],
       [100,  90,  80,  70,  50],
       [ 70,  70,  60,  50,  85]])

Jika inputnya seperti array di atas, berarti kita memiliki `3` siswa. Setiap siswa memiliki `5` nilai.

- Nilai siswa pertama adalah: 80, 50, 80, 60, 70. Dari awal hingga akhir, siswa Lulus, Gagal, Lulus, Gagal, Lulus
- Nilai siswa kedua adalah: 100, 90, 80, 70, 50. Dari pertama sampai terakhir, siswa Lulus, Lulus, Lulus, Lulus, Gagal
- Nilai siswa ketiga adalah: 70, 70, 60, 50, 80. Dari awal hingga akhir, siswa Lulus, Lulus, Gagal, Gagal, Lulus

Kemudian, ketika `grade(input_array)` dijalankan, output Anda akan seperti ini:
`[[P,F,P,F,P],[P,P,P,P,F],[P,P,F,F,P]]`

#### Example 2:

In [ ]:
input_array = np.array([[100,50,100],
                       [70,70,70],
                       [40,80,40],
                       [50,55,80]])
input_array

array([[100,  50, 100],
       [ 70,  70,  70],
       [ 40,  80,  40],
       [ 50,  55,  80]])

Jika inputnya seperti array di atas, berarti kita memiliki `4` siswa . Setiap siswa memiliki `3` nilai. Kemudian, ketika fungsi `grade(input_array)` dijalankan, output Anda akan seperti ini:

`[[P,F,P], [P,P,P], [F,P,F], [F,F,P]]`

In [ ]:
def grade(input_array):
    ### Write your solution here ###
    pass_marks = 70
    passing_array = np.where(input_array >= pass_marks, 'P', 'F')
    return passing_array.tolist()

In [ ]:
# Example 1
input_array = np.array([[80, 50, 80, 60, 70],
                       [100, 90, 80, 70, 50],
                       [70, 70, 60, 50, 85]])

output_array = grade(input_array)
print(output_array)

[['P', 'F', 'P', 'F', 'P'], ['P', 'P', 'P', 'P', 'F'], ['P', 'P', 'F', 'F', 'P']]


In [ ]:
# Example 2
input_array = np.array([[100,50,100],
                       [70,70,70],
                       [40,80,40],
                       [50,55,80]])
input_array

array([[100,  50, 100],
       [ 70,  70,  70],
       [ 40,  80,  40],
       [ 50,  55,  80]])

In [ ]:
grade(input_array)

[['P', 'F', 'P'], ['P', 'P', 'P'], ['F', 'P', 'F'], ['F', 'F', 'P']]

### Numpy Question 3

Nama fungsi Anda adalah `one_hot`, dan input fungsi Anda adalah array numpy.

Dalam tugas ini, Anda diminta untuk mengonversi array integer menjadi one hot encoding.

Ini berguna dalam machine learning dan bahkan kasus deep learning, di mana kita ingin melakukan eature engineering, represent categorical classes, dll.

Resource on one-hot-encoding: https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/

#### Example 1:

Jika array inputnya adalah `[2,3,1,2]` maka versi one hot encodingnya adalah:

`[[0,1,0], [0,0,1], [1,0,0], [0,1,0]]`

Penjelasan: ada 3 bilangan bulat unik: 1, 2, dan 3. Jika kita ingin merepresentasikannya dengan one-hot encoding, kita harus merepresentasikannya dalam `0 dan 1`.

Karena ada 3 bilangan bulat unik, kita merepresentasikannya dalam 3 urutan `0 dan 1`.

1 direpresentasikan sebagai `[1, 0, 0]`
2 direpresentasikan sebagai `[0, 1, 0]`
3 direpresentasikan sebagai `[0, 0, 1]`

Jadi, jika `input_array` adalah `np.array([2,3,1,2])`
Dan array diteruskan ke fungsi Anda ..

`one_hot(input_array)` sama dengan `array([[0,1,0], [0,0,1], [1,0,0], [0,1,0]])`

#### Example 2

Jika larik inputnya adalah `[4,2,1,3]` maka versi one hot encodingnya adalah:

`[[0,0,0,1], [0,1,0,0], [1,0,0,0], [0,0,1,0]]`

Penjelasan: ada 4 integer unik: 1, 2, 3, dan 4. Jika kita ingin merepresentasikannya dengan one-hot encoding, kita harus merepresentasikannya dalam `0 dan 1`.

Karena ada 4 integer unik, kita merepresentasikannya dalam 4 urutan `0 dan 1`.

1 direpresentasikan sebagai `[1, 0, 0, 0]`
2 direpresentasikan sebagai `[0, 1, 0, 0]`
3 direpresentasikan sebagai `[0, 0, 1, 0]`
4 direpresentasikan sebagai `[0, 0, 0, 1]`

Jadi, jika `input_array` adalah `np.array([4,2,1,3])`
Dan array diteruskan ke fungsi Anda ..

`one_hot(input_array)` sama dengan `array([[0,0,0,1], [0,1,0,0], [1,0,0,0], [0,0,1,0 ]])`


#### Constrains:

- Bilangan bulat dalam array input akan dimulai dengan 1.
- Bilangan bulat dalam array input tidak akan bernilai nol atau negatif.
- Bilangan bulat tidak akan dilewati (misalnya, array input tidak mungkin memiliki [4,1,2] karena 3 tidak ada).



In [ ]:
def one_hot(input_array):
    ### Write your solution here ###
    unique_values = np.unique(input_array)
    num_classes = len(unique_values)
    encoding = np.zeros((len(input_array), num_classes), dtype=int)
    for i, value in enumerate(input_array):
        index = np.where(unique_values == value)[0][0]
        encoding[i, index] = 1
    return encoding.tolist()

In [ ]:
# Example 1
input_array1 = np.array([2, 3, 1, 2])
output1 = one_hot(input_array1)
print(output1)

[[0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0]]


In [ ]:
# Example 2
input_array2 = np.array([4, 2, 1, 3])
output2 = one_hot(input_array2)
print(output2)

[[0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0]]


# **THANK YOU** :)